apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: default
data:
  default.conf: |
    server {
        listen 80;
        location / {
            return 200 'hello from $hostname\n';
        }
        location /stub_status {
            stub_status;
        }
    }